services:
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "6072:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=host.docker.internal
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=todo_list_backend
      - DB_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: