services:
  test:
    build: 
      context: ./backend
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=todo_list_backend
      - DB_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql
      - redis