FROM node:22-alpine

WORKDIR /usr/src/app

COPY package*.json tsconfig.json ./

RUN npm install

# No need to copy source files as we'll use a volume
# COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]