FROM node:22-alpine

WORKDIR /usr/src/app

# No need for npm install since we'll use local node_modules
# No need to copy anything since we'll mount everything

EXPOSE 3000

RUN npm install

CMD npm run dev & sleep 1 && npm run test:integration && wait