FROM node:22-alpine

WORKDIR /usr/src/app

EXPOSE 3000

# node_modules are excluded from mounting
# this way Linux-specific packages are installed
# in the Docker image itself
# it also means we need to rebuild it on every new dependency
CMD npm i && npm run dev